### ISSUE TITLE
Broken again

### ISSUE THREAD

**Issue by starwarsman981** [macedonga/beunblurred#56] opened 2024-10-26 01:52 UTC
Error 500 again when attempting to OTP. Also coupled with the absolutely INSANE verification method...

**Comment by tt-s8** [comment] 2024-10-26 08:04
Me too.(I tried it with a Japanese phone number.) And Recaptcha is hard to solve.

**Comment by macedonga** [comment] 2024-10-26 09:50
I think i know what the issue is: the server is making to many login requests
BeUnblurred works locally... So I'll implement proxies in the next few hours :-)

**Comment by macedonga** [comment] 2024-10-26 09:51
also, i can't do anything about the captcha :-(

**Comment by sveaalessxa** [comment] 2024-10-26 21:08
> Error 500 again when attempting to OTP. Also coupled with the absolutely INSANE verification method...

me too

**Comment by macedonga** [comment] 2024-10-27 10:14
I implemented proxies, but it still doesn't work on production. I tried on the server to run it in development mode (not on the beunblurred.co domain) and it works. So my guess is that:
1 - the captcha doesn't work on the beunblurred.co domain, but it does on localhost and ip addresses
2 - there is something going wrong when building the app (maybe sentry?)

**Comment by tt-s8** [comment] 2024-10-27 12:47
It is running in local. Thank you.

**Comment by reuddery** [comment] 2024-10-28 14:56
be unblurred still doesn't work

**Comment by reuddery** [comment] 2024-10-28 14:57
beunblurred still doesn't work

**Comment by macedonga** [comment] 2024-10-28 17:40
Should be fixed now!

**Closed by macedonga** 2024-10-28 17:40 UTC

**Comment by VCerceau** [comment] 2024-10-30 15:58
Still has error type 500 for me (🇫🇷 +33 numero)
