### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Mfb9909** [macedonga/beunblurred#18] opened 2024-01-31 13:03 UTC
![image](https://github.com/macedonga/beunblurred/assets/132620762/70ac443d-f88a-4141-9d89-20131c08073a)

**Comment by macedonga** [comment] 2024-01-31 14:12
Duplicate of #13. This is the reason it's not working with some phone numbers. I don't know the cause yet.

**Comment by Mfb9909** [comment] 2024-01-31 14:13
Ah I see, thanks for the update

**Closed by macedonga** 2024-01-31 14:12 UTC

**Comment by Mfb9909** [comment] 2024-02-10 22:47
Any fixes?
